---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zenith-mc
  namespace: {{ .Values.namespace }}
  labels:
    app: zenith-mc
    app.kubernetes.io/name: zenith-mc
    app.kubernetes.io/part-of: zenith
    app.kubernetes.io/component: mc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zenith-mc
