{{- if .Values.registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ include "zenith.namespace" . }}
  labels:
    {{- include "zenith.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "zenith.dockerconfigjson" . }}
{{- range $name, $tenant := .Values.tenants }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.registry.secretName }}
  namespace: {{ $tenant.namespace }}
  labels:
    {{- include "zenith.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "zenith.dockerconfigjson" $ }}
{{- end }}
{{- end }}
