---
apiVersion: v1
kind: Secret
metadata:
  name: zenith-secrets
  namespace: {{ include "zenith.namespace" . }}
  labels:
    {{- include "zenith.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 64) | quote }}
  admin-email: {{ .Values.secrets.adminEmail | quote }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
