server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        default_type application/json;
        add_header Cache-Control "no-store";
    }

    location /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok"}';
    }
}
