---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zenith-api
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        {{- if .Values.ingress.apisixEnabled }}
        - name: apisix-gateway
          namespace: apisix
          port: 9080
        {{- else if .Values.ingress.kongEnabled }}
        - name: kong-gateway-proxy
          namespace: kong
          port: 80
        {{- else }}
        - name: zenith-api
          port: {{ .Values.port }}
        {{- end }}
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zenith-api-redirect
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        {{- if .Values.ingress.apisixEnabled }}
        - name: apisix-gateway
          namespace: apisix
          port: 9080
        {{- else if .Values.ingress.kongEnabled }}
        - name: kong-gateway-proxy
          namespace: kong
          port: 80
        {{- else }}
        - name: zenith-api
          port: {{ .Values.port }}
        {{- end }}
