//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Project) DeepCopy() *Project {
	if in == nil { return nil }
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil { return nil }
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = new(ResourceQuota)
		**out = **in
	}
}

func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil { return nil }
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil { return nil }
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceQuota) DeepCopy() *ResourceQuota {
	if in == nil { return nil }
	out := new(ResourceQuota)
	*out = *in
	return out
}

// App deep copy
func (in *App) DeepCopyInto(out *App) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *App) DeepCopy() *App {
	if in == nil { return nil }
	out := new(App)
	in.DeepCopyInto(out)
	return out
}

func (in *App) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AppList) DeepCopyInto(out *AppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]App, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *AppList) DeepCopy() *AppList {
	if in == nil { return nil }
	out := new(AppList)
	in.DeepCopyInto(out)
	return out
}

func (in *AppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AppSpec) DeepCopyInto(out *AppSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(AppResources)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(HealthCheck)
		**out = **in
	}
	if in.AutoScale != nil {
		in, out := &in.AutoScale, &out.AutoScale
		*out = new(AutoScale)
		**out = **in
	}
	if in.BuildSource != nil {
		in, out := &in.BuildSource, &out.BuildSource
		*out = new(BuildSource)
		**out = **in
	}
}

func (in *AppSpec) DeepCopy() *AppSpec {
	if in == nil { return nil }
	out := new(AppSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AppResources) DeepCopyInto(out *AppResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

func (in *AppStatus) DeepCopyInto(out *AppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.LastDeployedAt != nil {
		in, out := &in.LastDeployedAt, &out.LastDeployedAt
		*out = (*in).DeepCopy()
	}
}

func (in *AppStatus) DeepCopy() *AppStatus {
	if in == nil { return nil }
	out := new(AppStatus)
	in.DeepCopyInto(out)
	return out
}

// Database deep copy
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Database) DeepCopy() *Database {
	if in == nil { return nil }
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

func (in *Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DatabaseList) DeepCopyInto(out *DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Database, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *DatabaseList) DeepCopy() *DatabaseList {
	if in == nil { return nil }
	out := new(DatabaseList)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.Storage = in.Storage.DeepCopy()
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(DatabaseResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil { return nil }
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseResources) DeepCopyInto(out *DatabaseResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil { return nil }
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// StorageBucket deep copy
func (in *StorageBucket) DeepCopyInto(out *StorageBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StorageBucket) DeepCopy() *StorageBucket {
	if in == nil { return nil }
	out := new(StorageBucket)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StorageBucketList) DeepCopyInto(out *StorageBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBucket, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *StorageBucketList) DeepCopy() *StorageBucketList {
	if in == nil { return nil }
	out := new(StorageBucketList)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StorageBucketSpec) DeepCopyInto(out *StorageBucketSpec) {
	*out = *in
	if in.LifecycleRules != nil {
		in, out := &in.LifecycleRules, &out.LifecycleRules
		*out = make([]LifecycleRule, len(*in))
		copy(*out, *in)
	}
	if in.CORSRules != nil {
		in, out := &in.CORSRules, &out.CORSRules
		*out = make([]CORSRule, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *StorageBucketSpec) DeepCopy() *StorageBucketSpec {
	if in == nil { return nil }
	out := new(StorageBucketSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageBucketStatus) DeepCopyInto(out *StorageBucketStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *StorageBucketStatus) DeepCopy() *StorageBucketStatus {
	if in == nil { return nil }
	out := new(StorageBucketStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CORSRule) DeepCopyInto(out *CORSRule) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedMethods != nil {
		in, out := &in.AllowedMethods, &out.AllowedMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// Domain deep copy
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Domain) DeepCopy() *Domain {
	if in == nil { return nil }
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

func (in *Domain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DomainList) DeepCopyInto(out *DomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Domain, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *DomainList) DeepCopy() *DomainList {
	if in == nil { return nil }
	out := new(DomainList)
	in.DeepCopyInto(out)
	return out
}

func (in *DomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *DomainSpec) DeepCopyInto(out *DomainSpec) {
	*out = *in
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLConfig)
		**out = **in
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNSConfig)
		**out = **in
	}
}

func (in *DomainSpec) DeepCopy() *DomainSpec {
	if in == nil { return nil }
	out := new(DomainSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DomainStatus) DeepCopyInto(out *DomainStatus) {
	*out = *in
	if in.CertificateExpiry != nil {
		in, out := &in.CertificateExpiry, &out.CertificateExpiry
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *DomainStatus) DeepCopy() *DomainStatus {
	if in == nil { return nil }
	out := new(DomainStatus)
	in.DeepCopyInto(out)
	return out
}

// AuthRealm deep copy
func (in *AuthRealm) DeepCopyInto(out *AuthRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AuthRealm) DeepCopy() *AuthRealm {
	if in == nil { return nil }
	out := new(AuthRealm)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AuthRealmList) DeepCopyInto(out *AuthRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthRealm, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *AuthRealmList) DeepCopy() *AuthRealmList {
	if in == nil { return nil }
	out := new(AuthRealmList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AuthRealmSpec) DeepCopyInto(out *AuthRealmSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]IdentityProvider, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]AuthClient, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(RealmSettings)
		(*in).DeepCopyInto(*out)
	}
}

func (in *AuthRealmSpec) DeepCopy() *AuthRealmSpec {
	if in == nil { return nil }
	out := new(AuthRealmSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthRealmStatus) DeepCopyInto(out *AuthRealmStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *AuthRealmStatus) DeepCopy() *AuthRealmStatus {
	if in == nil { return nil }
	out := new(AuthRealmStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *IdentityProvider) DeepCopyInto(out *IdentityProvider) {
	*out = *in
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
}

func (in *AuthClient) DeepCopyInto(out *AuthClient) {
	*out = *in
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RealmSettings) DeepCopyInto(out *RealmSettings) {
	*out = *in
	if in.PasswordPolicy != nil {
		in, out := &in.PasswordPolicy, &out.PasswordPolicy
		*out = new(PasswordPolicy)
		**out = **in
	}
}

// GitSync deep copy
func (in *GitSync) DeepCopyInto(out *GitSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GitSync) DeepCopy() *GitSync {
	if in == nil { return nil }
	out := new(GitSync)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GitSyncList) DeepCopyInto(out *GitSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitSync, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *GitSyncList) DeepCopy() *GitSyncList {
	if in == nil { return nil }
	out := new(GitSyncList)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GitSyncSpec) DeepCopyInto(out *GitSyncSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

func (in *GitSyncSpec) DeepCopy() *GitSyncSpec {
	if in == nil { return nil }
	out := new(GitSyncSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSyncStatus) DeepCopyInto(out *GitSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *GitSyncStatus) DeepCopy() *GitSyncStatus {
	if in == nil { return nil }
	out := new(GitSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// CrossplaneResource deep copy
func (in *CrossplaneResource) DeepCopyInto(out *CrossplaneResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *CrossplaneResource) DeepCopy() *CrossplaneResource {
	if in == nil { return nil }
	out := new(CrossplaneResource)
	in.DeepCopyInto(out)
	return out
}

func (in *CrossplaneResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *CrossplaneResourceList) DeepCopyInto(out *CrossplaneResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CrossplaneResource, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *CrossplaneResourceList) DeepCopy() *CrossplaneResourceList {
	if in == nil { return nil }
	out := new(CrossplaneResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *CrossplaneResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *CrossplaneResourceSpec) DeepCopyInto(out *CrossplaneResourceSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
	if in.WriteConnectionSecretToRef != nil {
		in, out := &in.WriteConnectionSecretToRef, &out.WriteConnectionSecretToRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

func (in *CrossplaneResourceSpec) DeepCopy() *CrossplaneResourceSpec {
	if in == nil { return nil }
	out := new(CrossplaneResourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CrossplaneResourceStatus) DeepCopyInto(out *CrossplaneResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *CrossplaneResourceStatus) DeepCopy() *CrossplaneResourceStatus {
	if in == nil { return nil }
	out := new(CrossplaneResourceStatus)
	in.DeepCopyInto(out)
	return out
}

