apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenith-landing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: landing=registry.stage.freezenith.com/zenith-stage/zenith-landing
    argocd-image-updater.argoproj.io/landing.update-strategy: latest
    argocd-image-updater.argoproj.io/landing.helm.image-name: image
    argocd-image-updater.argoproj.io/landing.helm.image-tag: imageTag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/taikuri-infra/Zenith.git
    targetRevision: staging
    path: infra/helm/zenith-landing
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: imagePullSecret
          value: harbor-registry
        - name: imageRegistry
          value: registry.stage.freezenith.com/zenith-stage
  destination:
    server: https://kubernetes.default.svc
    namespace: zenith-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
