apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenith-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/taikuri-infra/Zenith.git
    targetRevision: staging
    path: infra/helm/zenith-web
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: imagePullSecret
          value: harbor-registry
        - name: imageRegistry
          value: registry.stage.freezenith.com/zenith-stage
  destination:
    server: https://kubernetes.default.svc
    namespace: zenith-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
