apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "zenith.namespace" . }}
  labels:
    {{- include "zenith.labels" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
