apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.fullname" . }}-secrets
  namespace: {{ include "zenith.namespace" . }}
  labels:
    {{- include "zenith.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ default (randAlphaNum 64) .Values.api.env.JWT_SECRET | b64enc | quote }}
  hetzner-token: {{ default "" .Values.global.hetznerToken | b64enc | quote }}
