"use client";

import { Shell } from "@/components/shell";
import { StatusBadge } from "@/components/status-badge";
import { StatCard } from "@/components/stat-card";
import { ProgressBar } from "@/components/progress-bar";
import { DatabaseDetailSkeleton } from "@/components/loading-skeleton";
import { ErrorState } from "@/components/error-state";
import { useApi } from "@/hooks/use-api";
import { useToast } from "@/components/toast";
import { getApi } from "@/lib/get-api";
import { useParams } from "next/navigation";
import { useState } from "react";
import { Copy, Check, Eye, EyeOff, RotateCw, Download, AlertTriangle, Table2, Info, Trash2, ArrowLeft } from "lucide-react";
import { Modal } from "@/components/modal";
import { DatabaseExplorer } from "@/components/database-explorer";
import Link from "next/link";

const engineColors: Record<string, string> = {
  postgresql: "bg-blue-500/20 text-blue-400",
  mysql: "bg-orange-500/20 text-orange-400",
  mongodb: "bg-green-500/20 text-green-400",
  redis: "bg-red-500/20 text-red-400",
  rabbitmq: "bg-purple-500/20 text-purple-400",
  kafka: "bg-orange-500/20 text-orange-400",
};

function CopyField({ label, value, masked = false }: { label: string; value: string; masked?: boolean }) {
  const [copied, setCopied] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const displayValue = masked && !revealed ? "••••••••••••••••" : value;
  return (
    <div>
      <label className="mb-1 block text-[11px] font-medium text-neutral-500">{label}</label>
      <div className="flex items-center gap-2">
        <div className="flex-1 rounded-md bg-surface-200 px-3 py-2">
          <code className="text-xs text-white break-all font-mono">{displayValue}</code>
        </div>
        {masked && (
          <button
            onClick={() => setRevealed(!revealed)}
            className="shrink-0 rounded-md border border-border p-2 text-neutral-400 hover:text-white hover:border-neutral-500 transition-colors"
          >
            {revealed ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
          </button>
        )}
        <button
          onClick={() => {
            navigator.clipboard.writeText(value);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
          }}
          className="shrink-0 rounded-md border border-border p-2 text-neutral-400 hover:text-white hover:border-neutral-500 transition-colors"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
        </button>
      </div>
    </div>
  );
}

export default function DatabaseDetailPage() {
  const { toast } = useToast();
  const { name: dbId } = useParams<{ name: string }>();
  const { standaloneDatabases } = getApi();
  const [activeTab, setActiveTab] = useState<"overview" | "explorer">("overview");
  const [showResetModal, setShowResetModal] = useState(false);
  const [newPassword, setNewPassword] = useState<string | null>(null);
  const [resetting, setResetting] = useState(false);

  const [newConnStr, setNewConnStr] = useState<string | null>(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const handleResetPassword = async () => {
    setResetting(true);
    try {
      const result = await standaloneDatabases.resetPassword(dbId);
      setNewPassword(result.db_password);
      setNewConnStr(result.connection_string);
    } catch {
      toast("error", "Failed to reset database password");
    } finally {
      setResetting(false);
    }
  };

  const handleDelete = async () => {
    setDeleting(true);
    try {
      await standaloneDatabases.delete(dbId);
      toast("success", "Database deleted");
      window.location.href = "/databases";
    } catch {
      toast("error", "Failed to delete database");
    } finally {
      setDeleting(false);
    }
  };

  const handleDownloadEnv = (password?: string) => {
    if (!db) return;
    const pw = password ?? db.db_password ?? "";
    const connStr = db.connection_string || `${db.engine}://${db.db_user}:${pw}@${db.host}:${db.port}/${db.db_name}`;
    const urlKey = db.engine === "redis" ? "REDIS_URL" : db.engine === "mysql" ? "MYSQL_URL" : db.engine === "mongodb" ? "MONGODB_URL" : db.engine === "rabbitmq" ? "RABBITMQ_URL" : db.engine === "kafka" ? "KAFKA_URL" : "DATABASE_URL";
    const envContent = [
      `# Database credentials for ${db.name}`,
      `# Generated by Zenith on ${new Date().toISOString()}`,
      ``,
      `${urlKey}=${connStr}`,
      `DB_HOST=${db.host}`,
      `DB_PORT=${db.port}`,
      `DB_NAME=${db.db_name}`,
      `DB_USER=${db.db_user}`,
      `DB_PASSWORD=${pw}`,
    ].join("\n");
    const blob = new Blob([envContent + "\n"], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${db.name}.env`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const {
    data: db,
    loading,
    error,
    refetch,
  } = useApi(() => standaloneDatabases.get(dbId), [dbId]);

  if (loading) {
    return (
      <Shell>
        <DatabaseDetailSkeleton />
      </Shell>
    );
  }

  if (error) {
    return (
      <Shell>
        <ErrorState message={error} onRetry={refetch} />
      </Shell>
    );
  }

  if (!db) {
    return (
      <Shell>
        <ErrorState message={`Database "${dbId}" not found`} />
      </Shell>
    );
  }

  const usagePercent = db.max_size_mb > 0 ? Math.round((db.size_mb / db.max_size_mb) * 100) : 0;

  return (
    <Shell>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div
              className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-sm font-bold ${
                engineColors[db.engine] ?? "bg-neutral-500/20 text-neutral-400"
              }`}
            >
              {db.engine[0].toUpperCase()}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-lg font-semibold text-white">{db.name}</h1>
                <span
                  className={`rounded-md px-2 py-0.5 text-xs font-medium capitalize ${
                    engineColors[db.engine] ?? "bg-neutral-500/20 text-neutral-400"
                  }`}
                >
                  {db.engine}
                </span>
                <StatusBadge status={db.status as "ready" | "provisioning" | "error" | "deleting"} />
                {!db.app_id && (
                  <span className="rounded-full bg-purple-500/15 px-2 py-0.5 text-[10px] font-medium text-purple-400">
                    Standalone
                  </span>
                )}
              </div>
              <p className="mt-0.5 text-sm text-neutral-500">
                {db.app_id ? (
                  <>
                    Linked to{" "}
                    <Link href={`/apps/${db.app_id}`} className="text-accent-400 hover:underline">
                      {db.app_id}
                    </Link>
                  </>
                ) : (
                  "Not linked to any app"
                )}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Link
              href="/databases"
              className="flex items-center gap-1.5 rounded-md border border-border bg-surface-200 px-3 py-1.5 text-xs text-neutral-400 hover:bg-surface-300 hover:text-white transition-colors"
            >
              <ArrowLeft className="h-3 w-3" />
              Back
            </Link>
            <button
              onClick={() => setShowDeleteModal(true)}
              className="flex items-center gap-1.5 rounded-md border border-red-500/30 bg-red-500/10 px-3 py-1.5 text-xs text-red-400 hover:bg-red-500/20 transition-colors"
            >
              <Trash2 className="h-3 w-3" />
              Delete
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 border-b border-border">
          <button
            onClick={() => setActiveTab("overview")}
            className={`flex items-center gap-2 px-4 py-2.5 text-sm transition-colors border-b-2 ${
              activeTab === "overview"
                ? "border-accent-500 text-accent-400 font-medium"
                : "border-transparent text-neutral-500 hover:text-white"
            }`}
          >
            <Info className="h-4 w-4" />
            Overview
          </button>
          {db.engine === "postgresql" && (
            <button
              onClick={() => setActiveTab("explorer")}
              className={`flex items-center gap-2 px-4 py-2.5 text-sm transition-colors border-b-2 ${
                activeTab === "explorer"
                  ? "border-accent-500 text-accent-400 font-medium"
                  : "border-transparent text-neutral-500 hover:text-white"
              }`}
            >
              <Table2 className="h-4 w-4" />
              Admin Panel
            </button>
          )}
        </div>

        {/* Tab Content */}
        {activeTab === "overview" && (
          <>
            {/* Connection Details */}
            <div className="rounded-lg border border-border bg-surface-100 p-4">
              <div className="mb-4 flex items-center justify-between">
                <h3 className="text-sm font-medium text-white">Connection Details</h3>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleDownloadEnv()}
                    className="flex items-center gap-1.5 rounded-md border border-border bg-surface-200 px-2.5 py-1 text-xs text-neutral-400 hover:bg-surface-300 hover:text-white transition-colors"
                  >
                    <Download className="h-3 w-3" />
                    Download .env
                  </button>
                  <button
                    onClick={() => setShowResetModal(true)}
                    className="flex items-center gap-1.5 rounded-md border border-border bg-surface-200 px-2.5 py-1 text-xs text-neutral-400 hover:bg-surface-300 hover:text-white transition-colors"
                  >
                    <RotateCw className="h-3 w-3" />
                    Reset Password
                  </button>
                </div>
              </div>
              <div className="space-y-3">
                <CopyField label="Host" value={db.host} />
                <CopyField label="Port" value={String(db.port)} />
                <CopyField label="Database" value={db.db_name} />
                <CopyField label="Username" value={db.db_user} />
                <CopyField label="Password" value={db.db_password ?? "••••••••"} masked />
                {db.connection_string && (
                  <CopyField label="Connection String" value={db.connection_string} masked />
                )}
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-4 gap-4">
              <StatCard
                label="Engine"
                value={db.engine}
                sub={`Port ${db.port}`}
              />
              <StatCard
                label="Storage Used"
                value={`${db.size_mb} MB`}
                sub={`of ${db.max_size_mb} MB`}
              />
              <StatCard label="Port" value={db.port} sub="listening" />
              <StatCard
                label="Created"
                value={new Date(db.created_at).toLocaleDateString()}
              />
            </div>

            {/* Usage bar */}
            {db.max_size_mb > 0 && (
              <div className="rounded-lg border border-border bg-surface-100 p-4">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-sm font-medium text-white">Storage Usage</h3>
                  <span className="text-xs text-neutral-400">{usagePercent}%</span>
                </div>
                <ProgressBar percent={usagePercent} />
                <p className="mt-2 text-xs text-neutral-500">
                  {db.size_mb} MB used of {db.max_size_mb} MB allocated
                </p>
              </div>
            )}
          </>
        )}

        {activeTab === "explorer" && (
          <DatabaseExplorer dbId={db.id} engine={db.engine} />
        )}
      </div>

      {/* Reset Password Modal */}
      {showResetModal && !newPassword && (
        <Modal title="Reset Database Password" onClose={() => setShowResetModal(false)}>
          <div className="space-y-4">
            <div className="flex items-start gap-3 rounded-lg border border-amber-500/30 bg-amber-500/5 px-4 py-3">
              <AlertTriangle className="h-4 w-4 text-amber-400 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-medium text-amber-300">This will invalidate the current password</p>
                <p className="text-xs text-amber-400/70 mt-0.5">
                  All applications using the current credentials will lose access. Make sure to update your connection strings.
                </p>
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setShowResetModal(false)}
                className="rounded-lg border border-border px-4 py-2 text-sm text-neutral-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleResetPassword}
                disabled={resetting}
                className="flex items-center gap-2 rounded-lg bg-red-500 px-4 py-2 text-sm font-medium text-white hover:bg-red-600 transition-colors disabled:opacity-50"
              >
                {resetting && <RotateCw className="h-4 w-4 animate-spin" />}
                {resetting ? "Resetting..." : "Reset Password"}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* Delete Confirmation Modal */}
      {showDeleteModal && (
        <Modal title="Delete Database" onClose={() => setShowDeleteModal(false)}>
          <div className="space-y-4">
            <div className="flex items-start gap-3 rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3">
              <AlertTriangle className="h-4 w-4 text-red-400 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-medium text-red-300">This action is irreversible</p>
                <p className="text-xs text-red-400/70 mt-0.5">
                  The database <strong>{db.name}</strong> and all its data will be permanently deleted.
                </p>
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setShowDeleteModal(false)}
                className="rounded-lg border border-border px-4 py-2 text-sm text-neutral-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="flex items-center gap-2 rounded-lg bg-red-500 px-4 py-2 text-sm font-medium text-white hover:bg-red-600 transition-colors disabled:opacity-50"
              >
                {deleting && <RotateCw className="h-4 w-4 animate-spin" />}
                {deleting ? "Deleting..." : "Delete Database"}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* New Password Modal — shown after reset */}
      {newPassword && (
        <Modal title="Password Reset" onClose={() => { setNewPassword(null); setNewConnStr(null); setShowResetModal(false); }}>
          <div className="space-y-4">
            <div className="flex items-start gap-3 rounded-lg border border-amber-500/30 bg-amber-500/5 px-4 py-3">
              <AlertTriangle className="h-4 w-4 text-amber-400 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-medium text-amber-300">Save your new password now</p>
                <p className="text-xs text-amber-400/70 mt-0.5">
                  This password will not be shown again.
                </p>
              </div>
            </div>

            <CopyField label="New Password" value={newPassword} />
            <CopyField label="Connection String" value={newConnStr || `${db.engine}://${db.db_user}:${newPassword}@${db.host}:${db.port}/${db.db_name}`} />

            <div className="flex items-center justify-between pt-2">
              <button
                onClick={() => handleDownloadEnv(newPassword)}
                className="flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm text-neutral-400 hover:text-white hover:border-neutral-500 transition-colors"
              >
                <Download className="h-4 w-4" />
                Download .env
              </button>
              <button
                onClick={() => { setNewPassword(null); setShowResetModal(false); }}
                className="rounded-lg bg-accent-500 px-4 py-2 text-sm font-medium text-white hover:bg-accent-600 transition-colors"
              >
                I&apos;ve saved my password
              </button>
            </div>
          </div>
        </Modal>
      )}
    </Shell>
  );
}
