package install

import (
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/dotechhq/zenith/cli/internal/tlscert"
)

// tlsMode returns the effective TLS mode for a non-localhost compose install,
// defaulting to HTTP-01 (the reachable-public-domain case) when unset.
func tlsMode(cfg *Config) string {
	switch cfg.TLSMode {
	case TLSDNS01, TLSSelfSigned, TLSHTTP01:
		return cfg.TLSMode
	default:
		return TLSHTTP01
	}
}

// generateTraefikStaticConfig renders /etc/traefik/traefik.yml for the given mode.
//
// The certificate resolver is attached to the websecure *entrypoint* rather than
// to individual routers, so no router (dashboard, API, or a deployed user app)
// names a resolver — they only enable `tls`. That is what lets the self-signed
// mode work: with no resolver defined, Traefik serves the default certificate
// (our leaf, supplied via the file provider), and no router errors out.
func generateTraefikStaticConfig(mode, acmeEmail string) string {
	var b strings.Builder
	b.WriteString("# Generated by `zen install --edition compose`. Do not edit by hand;\n")
	b.WriteString("# re-run the installer to change the TLS mode.\n")
	b.WriteString("entryPoints:\n")
	b.WriteString("  web:\n")
	b.WriteString("    address: \":80\"\n")
	b.WriteString("    http:\n")
	b.WriteString("      redirections:\n")
	b.WriteString("        entryPoint:\n")
	b.WriteString("          to: websecure\n")
	b.WriteString("          scheme: https\n")
	b.WriteString("  websecure:\n")
	b.WriteString("    address: \":443\"\n")
	if mode != TLSSelfSigned {
		// ACME modes: every TLS router on this entrypoint uses the `le` resolver
		// unless it names its own (none do).
		b.WriteString("    http:\n")
		b.WriteString("      tls:\n")
		b.WriteString("        certResolver: le\n")
	}
	b.WriteString("providers:\n")
	b.WriteString("  docker:\n")
	b.WriteString("    exposedByDefault: false\n")
	b.WriteString("    network: zenith_default\n")
	b.WriteString("  file:\n")
	b.WriteString("    directory: /etc/traefik/dynamic\n")
	b.WriteString("    watch: true\n")

	switch mode {
	case TLSHTTP01:
		b.WriteString("certificatesResolvers:\n")
		b.WriteString("  le:\n")
		b.WriteString("    acme:\n")
		fmt.Fprintf(&b, "      email: %q\n", acmeEmail)
		b.WriteString("      storage: /letsencrypt/acme.json\n")
		b.WriteString("      httpChallenge:\n")
		b.WriteString("        entryPoint: web\n")
	case TLSDNS01:
		b.WriteString("certificatesResolvers:\n")
		b.WriteString("  le:\n")
		b.WriteString("    acme:\n")
		fmt.Fprintf(&b, "      email: %q\n", acmeEmail)
		b.WriteString("      storage: /letsencrypt/acme.json\n")
		b.WriteString("      dnsChallenge:\n")
		b.WriteString("        provider: cloudflare\n")
	}
	return b.String()
}

// generateTraefikCertsConfig renders the file-provider dynamic config that makes
// the self-signed leaf the default certificate Traefik serves. The PEM files
// live under /etc/traefik/certs (NOT the watched dynamic dir) — the file
// provider parses every file in its directory as config, so a stray .crt there
// would spam parse errors.
func generateTraefikCertsConfig() string {
	return "" +
		"tls:\n" +
		"  stores:\n" +
		"    default:\n" +
		"      defaultCertificate:\n" +
		"        certFile: /etc/traefik/certs/zenith.crt\n" +
		"        keyFile: /etc/traefik/certs/zenith.key\n" +
		"  certificates:\n" +
		"    - certFile: /etc/traefik/certs/zenith.crt\n" +
		"      keyFile: /etc/traefik/certs/zenith.key\n"
}

// writeFileB64 writes content to path on the target with owner-only perms,
// base64-encoded so arbitrary bytes survive the shell round-trip.
func writeFileB64(r runner, path, content string) error {
	enc := base64.StdEncoding.EncodeToString([]byte(content))
	if out, err := r.Run(fmt.Sprintf("umask 077 && (echo %s | base64 -d) > %s", enc, path)); err != nil {
		return fmt.Errorf("write %s: %w\n%s", path, err, out)
	}
	return nil
}

// composeConfigureTLS writes the Traefik static config for the chosen mode and,
// for self-signed installs, generates the local CA + leaf and drops them where
// Traefik's file provider serves them. Runs for every non-localhost install
// (including the free subdomain, which is HTTP-01).
func composeConfigureTLS(cfg *Config) error {
	if cfg.DryRun {
		return nil
	}
	r, err := newRunner(cfg)
	if err != nil {
		return err
	}
	defer r.Close()

	dir := composeInstallDir(cfg)
	if err := validateInstallDir(dir); err != nil {
		return err
	}
	if out, err := r.Run(fmt.Sprintf("mkdir -p %s/traefik/dynamic %s/traefik/certs", dir, dir)); err != nil {
		return fmt.Errorf("prepare traefik dir: %w\n%s", err, out)
	}

	mode := tlsMode(cfg)
	if err := writeFileB64(r, dir+"/traefik/traefik.yml", generateTraefikStaticConfig(mode, acmeEmail(cfg))); err != nil {
		return err
	}

	if mode != TLSSelfSigned {
		return nil
	}
	return writeSelfSignedCerts(cfg, r, dir)
}

// acmeEmail is the contact address Let's Encrypt registers for renewal notices.
func acmeEmail(cfg *Config) string {
	if cfg.AdminEmail != "" {
		return cfg.AdminEmail
	}
	if cfg.Domain != "" && cfg.Domain != "localhost" {
		return "admin@" + cfg.Domain
	}
	return ""
}

// writeSelfSignedCerts generates a local CA + leaf for cfg.Domain, installs them
// for Traefik, and fetches the CA certificate back to the operator's machine so
// they can import it into their trust store.
func writeSelfSignedCerts(cfg *Config, r runner, dir string) error {
	caCert, caKey, err := tlscert.GenerateCA()
	if err != nil {
		return err
	}
	leaf, leafKey, err := tlscert.GenerateLeaf(caCert, caKey, cfg.Domain)
	if err != nil {
		return err
	}
	certs := dir + "/traefik/certs"
	files := map[string]string{
		certs + "/zenith.crt":              string(leaf),
		certs + "/zenith.key":              string(leafKey),
		certs + "/zenith-ca.crt":           string(caCert),
		certs + "/zenith-ca.key":           string(caKey),
		dir + "/traefik/dynamic/certs.yml": generateTraefikCertsConfig(),
	}
	for path, content := range files {
		if err := writeFileB64(r, path, content); err != nil {
			return err
		}
	}
	// Hand the CA back to the operator locally, regardless of local/SSH target.
	cfg.CACertPEM = string(caCert)
	return nil
}
