package deploy

import (
	"fmt"

	"github.com/dotechhq/zenith/services/api/internal/entities"
)

// GenerateDockerfile returns a Dockerfile content for the given framework.
// If the repo already has a Dockerfile (framework == dockerfile), this should not be called.
func GenerateDockerfile(framework entities.Framework, appName string, port int) (string, error) {
	switch framework {
	case entities.FrameworkNextJS:
		return dockerfileNextJS(port), nil
	case entities.FrameworkGo:
		return dockerfileGo(appName, port), nil
	case entities.FrameworkPython:
		return dockerfilePython(port), nil
	case entities.FrameworkDjango:
		return dockerfileDjango(port), nil
	case entities.FrameworkFlask:
		return dockerfileFlask(port), nil
	case entities.FrameworkRails:
		return dockerfileRails(port), nil
	case entities.FrameworkExpress:
		return dockerfileExpress(port), nil
	case entities.FrameworkStatic:
		return dockerfileStatic(), nil
	case entities.FrameworkDockerfile:
		return "", fmt.Errorf("repo has its own Dockerfile, no generation needed")
	default:
		return "", fmt.Errorf("unsupported framework: %s — provide a Dockerfile", framework)
	}
}

func dockerfileNextJS(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Next.js
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=%d
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
USER 1001
EXPOSE %d
CMD ["node", "server.js"]
`, port, port)
}

func dockerfileGo(appName string, port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Go
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/app ./...

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /bin/app .
ENV PORT=%d
USER 1001
EXPOSE %d
CMD ["./app"]
`, port, port)
}

func dockerfilePython(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Python
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=%d
USER 1001
EXPOSE %d
CMD ["python", "main.py"]
`, port, port)
}

func dockerfileDjango(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Django
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python manage.py collectstatic --noinput 2>/dev/null || true
ENV PORT=%d
USER 1001
EXPOSE %d
CMD ["gunicorn", "--bind", "0.0.0.0:%d", "--workers", "2", "config.wsgi:application"]
`, port, port, port)
}

func dockerfileFlask(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Flask
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=%d
USER 1001
EXPOSE %d
CMD ["gunicorn", "--bind", "0.0.0.0:%d", "--workers", "2", "app:app"]
`, port, port, port)
}

func dockerfileRails(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Rails
FROM ruby:3.3-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test
COPY . .
RUN bundle exec rake assets:precompile 2>/dev/null || true
ENV PORT=%d
ENV RAILS_ENV=production
USER 1001
EXPOSE %d
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
`, port, port)
}

func dockerfileExpress(port int) string {
	return fmt.Sprintf(`# Auto-generated by Zenith — Node.js/Express
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
ENV PORT=%d
ENV NODE_ENV=production
USER 1001
EXPOSE %d
CMD ["node", "index.js"]
`, port, port)
}

func dockerfileStatic() string {
	return `# Auto-generated by Zenith — Static Site
FROM nginx:1.25-alpine
COPY . /usr/share/nginx/html
COPY <<'EOF' /etc/nginx/conf.d/default.conf
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
EOF
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`
}
