---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zenith-web
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "zenith.hostMatch" .Values.ingress.hosts }}
      kind: Rule
      services:
        - name: zenith-web
          port: {{ .Values.port }}
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zenith-web-redirect
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "zenith.hostMatch" .Values.ingress.hosts }}
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: zenith-web
          port: {{ .Values.port }}
